language: go
go:
  - 1.10.x
  - 1.11.x
go_import_path: arp242.net/singlepage
notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/go-build
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/github.com/teamwork/singlepage
  - ./bin/test -race ./...
  - ./bin/coverage ./...
  - ./bin/lint ./...
